export const CREATE_TRADE = 'TRADE.CREATE_TRADE';
export const SHOW_TRADE = 'TRADE.SHOW_TRADE';
export const DELETE_TRADE = 'TRADE.DELETE_TRADE';
export const EDIT_TRADE = 'TRADE.EDIT_TRADE';
export const LOADING = 'TRADE.LOADING';
export const INIT_ERROR = 'TRADE.INIT_ERROR';
export const INIT_TRADES = 'TRADE.INIT_TRADES';
export const SHOW_RIGHT_PANEL = 'TRADE.SHOW_RIGHT_PANEL';
export const SET_SELECTED = 'TRADE.SET_SELECTED';

export const INIT_COMMODITIES = 'TRADE.INIT_COMMODITIES'
export const INIT_LOCATIONS = 'TRADE.INIT_LOCATIONS'
export const INIT_COUNTERPARTIES = 'TRADE.INIT_COUNTERPARTIES'
export const INIT_PRICES = 'TRADE.INIT_PRICES'