export const CREATE_TRADE = 'TRADE.CREATE_TRADE';
export const SHOW_TRADE = 'TRADE.SHOW_TRADE';
export const DELETE_TRADE = 'TRADE.DELETE_TRADE';
export const EDIT_TRADE = 'TRADE.EDIT_TRADE';
export const LOADING = 'TRADE.LOADING';
export const INIT_ERROR = 'TRADE.INIT_ERROR';
export const SHOW_RIGHT_PANEL = 'TRADE.SHOW_RIGHT_PANEL';
export const SET_SELECTED = 'TRADE.SET_SELECTED';

// INIT_DATA
export const INIT_TRADES = 'TRADE.INIT_TRADES';
export const INIT_COMMODITIES = 'TRADE.INIT_COMMODITIES'
export const INIT_LOCATIONS = 'TRADE.INIT_LOCATIONS'
export const INIT_COUNTERPARTIES = 'TRADE.INIT_COUNTERPARTIES'
export const INIT_PRICES = 'TRADE.INIT_PRICES'
export const DATA_LOAD_COMPLETE = 'TRADE.DATA_LOAD_COMPLETE'

//SEARCH FORM ACTIONS
export const UPDATE_SEARCH_FORM_STATE = 'TRADE.UPDATE_SEARCH_FORM_STATE'
export const SET_SEARCH_MODE = 'TRADE.SET_SEARCH_MODE'
export const RESET_SEARCH_MODE = 'TRADE.RESET_SEARCH_MODE'

//TRADE FORM ACTIONS
export const UPDATE_TRADE_FORM_STATE = 'TRADE.UPDATE_TRADE_FORM_STATE'

//MARKET DATA UPDATE ACTIONS
export const UPDATE_MARKET_DATA = 'TRADE.UPDATE_MARKET_DATA'