export const LOADING = 'MARKETDATA.LOADING';
export const INIT_ERROR = 'MARKETDATA.INIT_ERROR';
export const INIT_PRICES = 'MARKETDATA.INIT_PRICES';
export const UPDATE_MARKET_DATA = 'MARKETDATA.UPDATE_PRICES';
